Add postcode overrides for tests
alphagov/govuk-shielded-vulnerable-people-service pull request #251
Opened 2020-12-23 18:34 UTC by sh31

Update get_addresses_from_postcode to return an address for a postcode in the

POSTCODE_TIER_OVERRIDE. The street number is set as the tier from the POSTCODE_TIER_OVERRIDE variable.

Update set_is_postcode_in_england to return True for postcodes in POSTCODE_TIER_OVERRIDE
Update set_location_tier to set tier from value in the POSTCODE_TIER_OVERRIDE app config variable

2020-12-24 08:54 UTC, sanisc requested changes

2020-12-24 08:54 UTC, sanisc commented on concourse/pipeline.yml
> +          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
this value needs to be passed to smoke tests and end 2 end tests as well

2020-12-24 08:54 UTC, sanisc commented on vulnerable_people_form/form_pages/shared/session.py
> +    postcode = session["postcode"]
i would do this outside of the session where it is called so for example.

```
def update_is_postcode_in_england(postcode, app):
    postcode_in_england = is_postcode_in_england(postcode)

    if postcode in app.config["POSTCODE_TIER_OVERRIDE"]:
        postcode_in_england = True

    set_is_postcode_in_england(postcode_in_england)
```

2020-12-24 08:54 UTC, sanisc commented on vulnerable_people_form/integrations/postcode_lookup_helper.py
> +    if postcode in current_app.config["POSTCODE_TIER_OVERRIDE"]:
i don't think we should be skipping the call to ODS as that defies what the smoke test and e2e should do. Also i would leave this file and do the override where it is called. See the code below of what  i mean for the address_look.py.

2020-12-24 08:54 UTC, sanisc commented on vulnerable_people_form/integrations/postcode_lookup_helper.py
> +            "text": f"{current_app.config['POSTCODE_TIER_OVERRIDE'][postcode]}, Test Lane, City, {postcode}",
```
_ADDRESS_ERROR_MESSAGES = {
    postcode_lookup_helper.PostcodeNotFound.__name__: "Could not find postcode, please enter your address manually",
    postcode_lookup_helper.NoAddressesFoundAtPostcode.__name__: "No addresses found for {}, please enter your address manually",
    postcode_lookup_helper.ErrorFindingAddress.__name__: "An error has occurred, please enter your address manually"
}


@form.route("/address-lookup", methods=["GET"])
def get_address_lookup():
    postcode = session.get("postcode")
    if not postcode:
        postcode = form_answers()["support_address"]["postcode"]
    try:
        addresses = postcode_lookup_helper.get_addresses_from_postcode(postcode)
    except (postcode_lookup_helper.PostcodeNotFound, postcode_lookup_helper.NoAddressesFoundAtPostcode, postcode_lookup_helper.ErrorFindingAddress) as e:
        if postcode in current_app.config["POSTCODE_TIER_OVERRIDE"]:
            addresses = _create_test_address(postcode)
        else:
            session["error_items"] = {
                **session.setdefault("error_items", {}),
                "support_address": {"postcode": _ADDRESS_ERROR_MESSAGES[e.__class__.__name__].format(postcode)},
            }
            return redirect("/support-address")

    prev_path = append_querystring_params("/postcode-eligibility")

    return render_template_with_title(
        "address-lookup.html",
        previous_path=prev_path,
        postcode=postcode,
        addresses=addresses,
        **get_errors_from_session("postcode"),
    )


def _create_test_address(postcode):
    return [{
        "text": f"{current_app.config['POSTCODE_TIER_OVERRIDE'][postcode]}, Test Lane, City, {postcode}",
        "value": json.dumps({"uprn": 10000000,
                             "town_city": "Test",
                             "postcode": postcode,
                             "building_and_street_line_1": f"{current_app.config['POSTCODE_TIER_OVERRIDE'][postcode]} Test Lane",
                             # noqa
                             "building_and_street_line_2": ""})
    }]
```

2020-12-24 08:54 UTC, sanisc commented on concourse/pipeline.yml
> +          POSTCODE_TIER_OVERRIDE: ((svp-form/postcode-tier-override))
also the behave tests need updating to read that value and inject it as these are supposed to secret values

2020-12-24 08:54 UTC, sanisc commented on instance/config.py.sample.dev
> +POSTCODE_TIER_OVERRIDE = '{"TE11RR":1, "TE22RR" : 2, "TE33RR": 3, "TE44RR":4}'
tier 1 and 2 are treated the same just keep tier 2 in this collection

2020-12-31 11:39 UTC, sanisc requested changes

2020-12-31 11:39 UTC, sanisc commented on vulnerable_people_form/form_pages/shared/session.py
> +    postcode = session["postcode"]
i would move this logic in the location_tier.py just like the above change made for `update_is_postcode_in_england`

2020-12-31 11:39 UTC, sanisc commented on instance/config.py.sample.dev
> +POSTCODE_TIER_OVERRIDE = '{"TE22RR" : 2, "TE33RR": 3, "TE44RR":4}'
the values in concourse should be different to this to avoid any leakage

2020-12-31 11:39 UTC, sanisc commented on behave/features/5.e2e_not_eligible_postcode.feature
> -        Then I am redirected to the "do-you-live-in-england" page
i would revert this change as this is for when the tiering logic is set to false in the app

2021-01-04 11:12 UTC, whpearson requested changes

2021-01-04 12:32 UTC, whpearson commented on vulnerable_people_form/form_pages/shared/location_tier.py
> +    if uprn == 999:
You could get the postcode from session here and do the logic on that. Which would enable us to set different tiers from uprns

2021-01-07 15:09 UTC, whpearson commented
It'd be nice to add  `- POSTCODE_TIER_OVERRIDE` to https://github.com/alphagov/govuk-shielded-vulnerable-people-service/blob/master/docker-compose.yml#L10 so that the environment variable was picked up when running e2e locally.

2021-01-08 09:55 UTC, whpearson approved these changes
This looks good locally, code makes sense. 

Only thing left before merging is getting the concourse values right.

2021-01-08 12:19 UTC, whpearson commented
I've just noticed that behave/features/e2e_test_features/01.simple_web_submission_entry.feature should probably change or be removed.

2021-01-08 16:16 UTC, whpearson approved these changes
Looks good and tested locally.

2021-01-08 17:19 UTC, sanisc commented on vulnerable_people_form/form_pages/address_lookup.py
> +        "value": json.dumps({"uprn": 999,
do we care about showing this uprn in plain text?

2021-01-12 14:55 UTC, merged