Remove shielding advice logic from front end
alphagov/govuk-shielded-vulnerable-people-service pull request #284
Opened 2021-01-25 15:08 UTC by sanisc

Shielding logic has all been moved to a backend store proc call so any front code can now be removed

2021-01-25 16:07 UTC, jk132 requested changes
Looks very reasonable in terms of stripping out the old code (aside from the one comment).
Assuming that the new implementation (with appropriate tests) is included elsewhere.

2021-01-25 16:07 UTC, jk132 commented on vulnerable_people_form/__init__.py
>  _DEFAULT_SHIELDING_ADVICE_FILE_PREFIX = "vulnerable_people_form/integrations/data/local-area-shielding-advice-"
This is no longer needed?

2021-01-25 21:08 UTC, sanisc commented on vulnerable_people_form/__init__.py
>  _DEFAULT_SHIELDING_ADVICE_FILE_PREFIX = "vulnerable_people_form/integrations/data/local-area-shielding-advice-"
Yes that has been removed now

2021-01-25 21:08 UTC, sanisc commented
> Looks very reasonable in terms of stripping out the old code (aside from the one comment).
> Assuming that the new implementation (with appropriate tests) is included elsewhere.

Correct the implementation is already in production - this was just the left over code that needed removing

2021-01-26 10:32 UTC, whpearson commented
I think we can cleanup the gatling tests, we have data for non tiering logic svp_submission_data.json and also we should remove reference to the TIERING logic flag from the load tests https://github.com/alphagov/govuk-shielded-vulnerable-people-service/blob/master/loadtests/src/test/scala/svp/ShieldedVulnerablePeople.scala#L10

2021-01-26 11:05 UTC, whpearson commented
I think I left some reference to la_shielding in the tests that can be removed as well. 

E.g.  in tests/form_pages/shared/test_location_tier.py there is test_update_location_status_by_postcode_should_update_session_when_tiering_logic_enabled which has   _current_app.shielding_advice.advice_from_la_shielding = lambda ladcode: shielding_advice

2021-01-26 12:45 UTC, sanisc commented
> I think I left some reference to la_shielding in the tests that can be removed as well.
> 
> E.g. in tests/form_pages/shared/test_location_tier.py there is test_update_location_status_by_postcode_should_update_session_when_tiering_logic_enabled which has _current_app.shielding_advice.advice_from_la_shielding = lambda ladcode: shielding_advice

These have been removed.

2021-01-26 13:31 UTC, whpearson approved these changes
Tested locally, automatically and manually. Changes look good.

2021-01-26 14:46 UTC, jk132 approved these changes
LGTM

2021-01-26 14:52 UTC, merged